[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "foreblocks"
version = "0.1.4"
description = "Modular Time Series Forecasting Library"
authors = [
    { name = "Laio Seman", email = "laioseman@gmail.com" }
]

readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
keywords = ["time series", "forecasting", "deep learning", "transformer", "lstm", "pytorch"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]

dependencies = [
    "torch>=1.12",
    "numpy",
    "scikit-learn",
    "matplotlib",
    "PyWavelets",
    "pytorch_wavelets",
    "wandb",
    "ipykernel>=6.29.5",
    "neuralforecast>=2.0.1",
    "openpyxl>=3.1.5",
    "statsmodels>=0.14.1",
    "tabulate>=0.9.0",
    "numba>=0.58.1",
    "google>=3.0.0",
    "pysr>=1.5.9",
    "ruptures>=1.1.9",
    "basedpyright>=1.33.0",
    "fastapi",
    "uvicorn",
    "pydantic",
]

[project.urls]
Homepage = "https://github.com/lseman/foreblocks"
Repository = "https://github.com/lseman/foreblocks"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["foreblocks*", "foretools*"]


[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = 2
float_to_top = true
combine_as_imports = true
skip_gitignore = true
filter_files = true

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
